version: '3'

services:
  postgres:
    image: postgres:12
    container_name: postgres_outbox_pattern
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pg_outbox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command:
      - "postgres"
      - "-c"
      - "effective_cache_size=1024MB"
    networks:
      - network-backend
    volumes:
      - ./srv/docker/postgresql:/var/lib/postgresql

networks:
  network-backend:
    driver: bridge