version: '3'

services:
  postgres:
    image: postgres:12
    container_name: postgres_outbox_pattern
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pg_outbox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command:
      - "postgres"
      - "-c"
      - "effective_cache_size=1024MB"
    networks:
      - network-backend
    volumes:
      - ./srv/docker/postgresql:/var/lib/postgresql

  rabbit:
    container_name: rabbitmq_outbox_pattern
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - network-backend

networks:
  network-backend:
    driver: bridge