DO $$
BEGIN
  CREATE TABLE OUTBOX (
    ID SERIAL PRIMARY KEY,
    AGGREGATE_ID UUID NOT NULL,
    AGGREGATE_TYPE VARCHAR(50) NOT NULL,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    PAYLOAD VARCHAR(5000) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    TENTATIVES INTEGER NOT NULL
  );
  COMMENT ON  TABLE OUTBOX IS 'Table to store Outbox events';
  COMMENT ON COLUMN OUTBOX.ID IS 'The identifier of an event';
  COMMENT ON COLUMN OUTBOX.AGGREGATE_ID IS 'The aggregate identifier';
  COMMENT ON COLUMN OUTBOX.AGGREGATE_TYPE IS 'The aggregate name';
  COMMENT ON COLUMN OUTBOX.EVENT_TYPE IS 'The type of the domain event';
  COMMENT ON COLUMN OUTBOX.PAYLOAD IS 'The content of the domain event';
  COMMENT ON COLUMN OUTBOX.CREATED_AT IS 'The datetime of the event store';
  COMMENT ON COLUMN OUTBOX.STATUS IS 'The event status in this table';
END
$$;