DO $$
BEGIN
  CREATE TABLE PRODUCT (
    PRODUCT_ID UUID NOT NULL,
    NAME VARCHAR(250) NOT NULL,
    CONSTRAINT PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID)
  );
  COMMENT ON  TABLE PRODUCT IS 'Table to store Products';
  COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS 'The product identifier';
  COMMENT ON COLUMN PRODUCT.NAME IS 'The product name';
END
$$;